# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Install IPFS
RUN apt-get update && apt-get install -y wget && apt-get install -y tar
         
RUN wget https://dist.ipfs.tech/kubo/v0.32.1/kubo_v0.32.1_linux-amd64.tar.gz && \
  tar -xvzf kubo_v0.32.1_linux-amd64.tar.gz && \
  cd kubo && \
  bash install.sh

# Create a directory for the app
WORKDIR /app

# Copy the FastAPI app
COPY requirements_web.txt ./requirements.txt
COPY ./webapp /app
COPY ./ipfs_utils /app/ipfs_utils

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Copy and set up the entrypoint script
COPY entrypoint_web.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Run the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
