# Use an official Python runtime as base
FROM python:3.11-slim

# Install IPFS
RUN apt-get update && apt-get install -y wget && apt-get install -y tar
         
RUN wget https://dist.ipfs.tech/kubo/v0.32.1/kubo_v0.32.1_linux-amd64.tar.gz && \
  tar -xvzf kubo_v0.32.1_linux-amd64.tar.gz && \
  cd kubo && \
  bash install.sh



# Set working directory
WORKDIR /app

ENV IPFS_PATH=/app/_local_cache/.ipfs

# Copy Python dependencies and install them
COPY requirements_app.txt ./requirements.txt
RUN pip install -r requirements.txt

# Copy application code and configuration
COPY ./app/ .


# Set the entrypoint to run our IPFSRunner application
CMD ["python", "main.py"]
