# Use an official Python runtime as base
FROM aidamian/py311_ipfs 

# Set working directory
WORKDIR /app

# ENV IPFS_PATH=/app/_local_cache/.ipfs

ARG CACHEBUST
RUN pip install --upgrade ratio1

# Copy application code and configuration
COPY ./app/ .


# Set the entrypoint to run our IPFSRunner application
CMD ["python", "main.py"]
